/**:
  ros__parameters:
    driver:
      i_transport_profile: LOW_BANDWIDTH
    rgb:
      i_low_bandwidth: true
    left:
      i_low_bandwidth: true
    right:
      i_low_bandwidth: true
    stereo:
      i_low_bandwidth: true
